### ISSUE TITLE
Function Calling features

### ISSUE THREAD

**Issue by csterwa** [spring-projects/spring-ai#1350]
For 1.0
- [ ] Customize invocation within function calling. Related issues, #1303 
- [ ] Fine-grained control over function invocation. Related issues, #1177, #1032, #991
- [ ] Exposing function context by supplying history. Related issues, #1202 
- [ ] Support more types in function calling. Related issues, #1118 

Post 1.0
- [ ] Annotation based function definition. Related issues, #1099, #1105
