### ISSUE TITLE
Improve Spring AI Bedrock Converse API Integration

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#1758]
Extend the [Spring AI Bedrock Converse](https://docs.spring.io/spring-ai/reference/api/bedrock-converse.html) integration with support for the following Bedrock [Converse](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html) and [ConverseStream](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ConverseStream.html) API features:

- [ ] [additionalModelRequestFields](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html#API_runtime_Converse_RequestSyntax) - Additional inference parameters that the model supports, beyond the base set of inference parameters that Converse and ConverseStream support in the inferenceConfig field.
- [ ] [ConverseMetrics](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ConverseMetrics.html) and [ConverseStreamMetrics](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ConverseStreamMetrics.html) - Metrics for a call to Converse and ConverseStream
- [ ] [Guardrail](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_GuardrailConfiguration.html), [Include a guardrail with Converse API](https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-use-converse-api.html) - to guard conversational apps that you create with the Converse

**Comment by starJammer** [comment]
I want to propose, in addition to the above, to add support for a 'guardContent' message type specifically for AWS. Guardrails on AWS, by default execute on the entire conversation and all messages. However, this is efficient and drives up cost significantly for ongoing conversations. 

[Refer to this document](https://github.com/aws/agent-toolkit-for-aws/blob/main/plugins/aws-core/skills/amazon-bedrock/references/guardrails.md) for how to apply the 'guardContent' message type. 

Essentially, guardContent message types should be supported so that AWS knows to apply the guardrail only to a limited number of messages in the message stack. This way, guardrails execute more quickly and efficiently and don't re-scan old messages in the conversation.

Example: This sort of global guardrail as suggested by @tzolov  will execute on all messages.
```json
{
  "guardrailConfig": {
    "guardrailIdentifier": "my-guardrail-id",
    "guardrailVersion": "1",
    "trace": "disabled"
  }
}
```

Example: This sort of guardContent message type will limit guardrail execution to only the specified scope.

```json
{
  "messages": [{
    "role": "user",
    "content": [
      {"text": "System context not evaluated by guardrail"},
      {"guardContent": {"text": {"text": "User input to evaluate"}}}
    ]
  }]
}
```

This is _impossible_ to implement right now because the Message implementation in Spring is effectively not extendable due to it's builder class being final and there being very little flexibility in the `BedrockProxyChatModel` class to support new message types. 

**If anyone has suggestions on how to implement this, other than copy/pasting the entire implementation into a new `CustomBedrockProxyChatModel` let me know!**

**Comment by hhhhzzzj** [comment]
I was tracing the Bedrock Converse path on current main and noticed a smaller way to move this issue forward.

`requestParameters` is already forwarded as `additionalModelRequestFields`, including the streaming path. On the response side, though, `toChatResponse()` reads both `additionalModelResponseFields()` and `metrics()`, but only the cache token counts are currently added to the response metadata.

Would a small PR just for the non-streaming response metadata make sense? I can keep guardContent, message-model changes, retry behavior, and streaming semantics out of it for now.

Do you have a preference for keeping the Bedrock values as native metadata or exposing a few normalized Spring AI metadata fields?
